.PHONY: install test run

install:
	@echo "Installing dependencies..."
	@pip install -r requirements.txt

test:
	@echo "Running tests..."
	@python -m unittest discover

run:
	@echo "Running application..."
	@python app.py 3 4
